// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Blogs = Collections['blogs']['schema']['_output']
export declare const blogs: Blogs[]

export type Projects = Collections['projects']['schema']['_output']
export declare const projects: Projects[]
